spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diary?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: 8181

#mybtais
#  mybatis:
#    mapper-locations=classpath: mapper/*Mapper.xml
#    configuration: map-underscore-to-camel-case=false
